<pre>
<?php
//Comparison Operators


//Error Control Operators - Handle error message
/**
 * If you have set a custom error handler function with set_error_handler() then it will still get called
 * If the track_errors feature is enabled, any error message generated by the expression will be saved in the variable $php_errormsg
 * http://php.net/manual/en/language.operators.errorcontrol.php
 */

/* Intentional file error */
$my_file = @file ('non_existent_file') or
    die ("Failed opening file: error was '$php_errormsg'");

// this works for any expression, not just functions:
$value = @$cache[$key];
// will not issue a notice if the index $key doesn't exist.


?>
</pre>